import Head from "next/head";
import Link from "next/link";

export default function Home() {
  //   const hello = api.example.hello.useQuery({ text: "Railway" });
  //   const clerkuser = api.example.me.useQuery();
//   const rule = api.rules.getAll.useQuery({ guild_id: "846599213440696360" });
//   const { mutate } = api.discord.hello.useMutation();

  return (
    <>
      <Head>
        <title>Nameless Bot</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-sky-900">
        <div className="h-screen">
          {/* <Navbar /> */}
          <div className="flex h-screen w-screen flex-col items-center bg-gradient-to-b from-sky-300 to-slate-200 py-48">
            <h1 className="text-5xl font-semibold">Nameless Bot</h1>
            <h2 className="mb-16 mt-8 text-3xl">
              Literally one of the bots of all time.
            </h2>
            <Link
              href="/dashboard"
              className="rounded-md bg-slate-200 px-4 py-2 text-2xl shadow-md transition  duration-200 hover:bg-slate-300 hover:shadow-lg"
            >
              Dashboard &rarr;
            </Link>
          </div>
        </div>
        <div className="flex h-screen flex-row items-center bg-gradient-to-b from-slate-200 to-sky-300">
          <div className="flex flex-col px-24">
            <h1 className="semibold text-3xl">
              I would put examples here if I understood graphic design
            </h1>
            <h1 className="semibold text-2xl">As it turns out, I do not.</h1>
          </div>
        </div>
      </main>
    </>
  );
}
